Adds bookshelf project
CodeYourFuture/group-projects pull request #9
Opened 2020-01-05 19:28 UTC by 40thieves

Adds a [bookshelf project](https://github.com/CodeYourFuture/bookshelf-project). Adapted from an old project repo to be consistent with the group-projects style. Feel free to open an issue/PR against that repo if you think it needs some changes.

I've made a (somewhat messy!) example implementation [here](https://github.com/CodeYourFuture/bookshelf-project/pull/39).

2020-01-05 19:29 UTC, 40thieves commented
@NateWr could you take a look at this? Finally got around to merging the changes into the bookshelf project repo.

2022-05-29 10:53 UTC, SallyMcGrath requested changes
Tiny changes to wording

2022-05-29 10:53 UTC, SallyMcGrath commented on bookshelf/readme.md
> +In this project, you will build a bookshelf app. The app structure and design have been put in place. To complete the app, you'll need to add functionality so that read and unread books can be shown
```suggestion
In this project, you will build a bookshelf app. The app structure and design are done. To complete the app, add functionality to: 
- show both read and unread books
- update the count of read books.
```

active voice, simpler sentences

2022-06-08 20:29 UTC, 40thieves commented
Thanks. Waiting until https://github.com/CodeYourFuture/group-project-bookshelf/pull/43 is approved before merging this.

2022-06-09 07:41 UTC, merged